// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: remote_rocksdb.proto
#ifndef GRPC_remote_5frocksdb_2eproto__INCLUDED
#define GRPC_remote_5frocksdb_2eproto__INCLUDED

#include "remote_rocksdb.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace remoterocksdb {

class RemoteRocksDBService final {
 public:
  static constexpr char const* service_full_name() {
    return "remoterocksdb.RemoteRocksDBService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // * 执行 CRUD 
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::remoterocksdb::Op, ::remoterocksdb::OpReply>> DoOp(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::remoterocksdb::Op, ::remoterocksdb::OpReply>>(DoOpRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::remoterocksdb::Op, ::remoterocksdb::OpReply>> AsyncDoOp(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::remoterocksdb::Op, ::remoterocksdb::OpReply>>(AsyncDoOpRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::remoterocksdb::Op, ::remoterocksdb::OpReply>> PrepareAsyncDoOp(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::remoterocksdb::Op, ::remoterocksdb::OpReply>>(PrepareAsyncDoOpRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // * 执行 CRUD 
      virtual void DoOp(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::remoterocksdb::Op,::remoterocksdb::OpReply>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::remoterocksdb::Op, ::remoterocksdb::OpReply>* DoOpRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::remoterocksdb::Op, ::remoterocksdb::OpReply>* AsyncDoOpRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::remoterocksdb::Op, ::remoterocksdb::OpReply>* PrepareAsyncDoOpRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::remoterocksdb::Op, ::remoterocksdb::OpReply>> DoOp(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::remoterocksdb::Op, ::remoterocksdb::OpReply>>(DoOpRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::remoterocksdb::Op, ::remoterocksdb::OpReply>> AsyncDoOp(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::remoterocksdb::Op, ::remoterocksdb::OpReply>>(AsyncDoOpRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::remoterocksdb::Op, ::remoterocksdb::OpReply>> PrepareAsyncDoOp(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::remoterocksdb::Op, ::remoterocksdb::OpReply>>(PrepareAsyncDoOpRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void DoOp(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::remoterocksdb::Op,::remoterocksdb::OpReply>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::remoterocksdb::Op, ::remoterocksdb::OpReply>* DoOpRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::remoterocksdb::Op, ::remoterocksdb::OpReply>* AsyncDoOpRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::remoterocksdb::Op, ::remoterocksdb::OpReply>* PrepareAsyncDoOpRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DoOp_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // * 执行 CRUD 
    virtual ::grpc::Status DoOp(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::remoterocksdb::OpReply, ::remoterocksdb::Op>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_DoOp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DoOp() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DoOp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoOp(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::remoterocksdb::OpReply, ::remoterocksdb::Op>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDoOp(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::remoterocksdb::OpReply, ::remoterocksdb::Op>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DoOp<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_DoOp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DoOp() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::remoterocksdb::Op, ::remoterocksdb::OpReply>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->DoOp(context); }));
    }
    ~WithCallbackMethod_DoOp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoOp(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::remoterocksdb::OpReply, ::remoterocksdb::Op>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::remoterocksdb::Op, ::remoterocksdb::OpReply>* DoOp(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_DoOp<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DoOp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DoOp() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DoOp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoOp(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::remoterocksdb::OpReply, ::remoterocksdb::Op>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DoOp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DoOp() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DoOp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoOp(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::remoterocksdb::OpReply, ::remoterocksdb::Op>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDoOp(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DoOp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DoOp() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->DoOp(context); }));
    }
    ~WithRawCallbackMethod_DoOp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoOp(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::remoterocksdb::OpReply, ::remoterocksdb::Op>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* DoOp(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace remoterocksdb


#endif  // GRPC_remote_5frocksdb_2eproto__INCLUDED
