// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: remote_rocksdb.proto

#include "remote_rocksdb.pb.h"
#include "remote_rocksdb.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace remoterocksdb {

static const char* RemoteRocksDBService_method_names[] = {
  "/remoterocksdb.RemoteRocksDBService/DoOp",
};

std::unique_ptr< RemoteRocksDBService::Stub> RemoteRocksDBService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RemoteRocksDBService::Stub> stub(new RemoteRocksDBService::Stub(channel, options));
  return stub;
}

RemoteRocksDBService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_DoOp_(RemoteRocksDBService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::remoterocksdb::Op, ::remoterocksdb::OpReply>* RemoteRocksDBService::Stub::DoOpRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::remoterocksdb::Op, ::remoterocksdb::OpReply>::Create(channel_.get(), rpcmethod_DoOp_, context);
}

void RemoteRocksDBService::Stub::async::DoOp(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::remoterocksdb::Op,::remoterocksdb::OpReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::remoterocksdb::Op,::remoterocksdb::OpReply>::Create(stub_->channel_.get(), stub_->rpcmethod_DoOp_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::remoterocksdb::Op, ::remoterocksdb::OpReply>* RemoteRocksDBService::Stub::AsyncDoOpRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::remoterocksdb::Op, ::remoterocksdb::OpReply>::Create(channel_.get(), cq, rpcmethod_DoOp_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::remoterocksdb::Op, ::remoterocksdb::OpReply>* RemoteRocksDBService::Stub::PrepareAsyncDoOpRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::remoterocksdb::Op, ::remoterocksdb::OpReply>::Create(channel_.get(), cq, rpcmethod_DoOp_, context, false, nullptr);
}

RemoteRocksDBService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RemoteRocksDBService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< RemoteRocksDBService::Service, ::remoterocksdb::Op, ::remoterocksdb::OpReply>(
          [](RemoteRocksDBService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::remoterocksdb::OpReply,
             ::remoterocksdb::Op>* stream) {
               return service->DoOp(ctx, stream);
             }, this)));
}

RemoteRocksDBService::Service::~Service() {
}

::grpc::Status RemoteRocksDBService::Service::DoOp(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::remoterocksdb::OpReply, ::remoterocksdb::Op>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace remoterocksdb

